Bugfix: Links View + pg_pool attribute error
 FIXED: Two critical bugs

1. Links View Missing:
    Error: 'schema must be one of: public, graphql_public'
    Created public.vw_links view
    Updated count_links_by_document() to use vw_links

2. Pipeline pg_pool Error:
    Error: 'KRMasterPipeline' object has no attribute 'pg_pool'
    Fixed: Use self.database_service.pg_pool
    Added hasattr() check for safety

Migration deployed: vw_links view for PostgREST access